name: Build deej Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20' # Adjust this version to the one your project needs

    - name: Set git commit and version tag
      id: vars
      run: |
        echo "::set-output name=GIT_COMMIT::$(git rev-list -1 --abbrev-commit HEAD)"
        echo "::set-output name=VERSION_TAG::$(git describe --tags --always)"
        
    - name: Build deej (release)
      run: |
        echo Building deej (release)...
        echo Embedding build-time parameters:
        echo - gitCommit ${{ steps.vars.outputs.GIT_COMMIT }}
        echo - versionTag ${{ steps.vars.outputs.VERSION_TAG }}
        echo - buildType release

        go build -o deej-release.exe -ldflags "-H=windowsgui -s -w -X main.gitCommit=${{ steps.vars.outputs.GIT_COMMIT }} -X main.versionTag=${{ steps.vars.outputs.VERSION_TAG }} -X main.buildType=release" ./pkg/deej/cmd
      shell: cmd

    - name: Upload built file (optional)
      uses: actions/upload-artifact@v3
      with:
        name: deej-release
        path: deej-release.exe
